/* ════════════════════════════════════════════════════════════════════════
   TELUGU TRANSLATION DICTIONARY  (English string → తెలుగు)

   Used by t('English') in i18n.jsx. If a string is missing here, the site
   falls back to English automatically — nothing breaks.

   ⚠ REVIEW NOTE: these translations are machine-assisted. A native Telugu
   speaker should proofread this file before it is treated as final. To find
   any strings still missing a translation, open the browser console and run:
       window.__TR_WARN = true
   then switch the site to తెలుగు — every missing string is logged.

   Organised by section. Keep keys EXACTLY matching the English source.
   ════════════════════════════════════════════════════════════════════════ */

window.TR = {

  // ─── SECTION 2: WHY CHANGE — comparison table ──────────────────────────
  'Feature': 'అంశం',
  'National (Union Govt)': 'జాతీయం (కేంద్ర ప్రభుత్వం)',
  'CM Prajavani': 'సీఎం ప్రజావాణి',
  'State — Hyderabad': 'రాష్ట్రం — హైదరాబాద్',
  'Collector Prajavani': 'కలెక్టర్ ప్రజావాణి',
  'District — weekly': 'జిల్లా — వారానికోసారి',
  'Adilabad Pilot': 'ఆదిలాబాద్ పైలట్',
  'Mandal — every Monday': 'మండలం — ప్రతి సోమవారం',

  'Filing Accessibility': 'ఫిర్యాదు దాఖలు సౌలభ్యం',
  'Acknowledgement Receipt': 'స్వీకృతి రసీదు',
  'Status Tracking': 'స్థితి ట్రాకింగ్',
  'Personal Hearing': 'వ్యక్తిగత విచారణ',
  'ATR Timeline': 'ATR గడువు',
  'Department SOPs': 'శాఖల SOPలు',
  'Auto-Escalation': 'స్వయంచాలక ఎస్కలేషన్',
  'Appeal Mechanism': 'అప్పీలు యంత్రాంగం',
  'Public Disclosure of Data': 'డేటా బహిరంగ వెల్లడి',
  'Independent Verification': 'స్వతంత్ర సత్యాపన',

  'Decentralised — web portal, CSCs, district collectorates': 'వికేంద్రీకృతం — వెబ్ పోర్టల్, CSCలు, జిల్లా కలెక్టరేట్లు',
  'Centralised — physical submission at Praja Bhavan, Hyderabad': 'కేంద్రీకృతం — హైదరాబాద్ ప్రజా భవన్‌లో ప్రత్యక్ష సమర్పణ',
  'Centralised at district level — physical submission at Collector office': 'జిల్లా స్థాయిలో కేంద్రీకృతం — కలెక్టర్ కార్యాలయంలో ప్రత్యక్ష సమర్పణ',
  'Decentralised — 16 mandal IFCs + online (since Oct 2025)': 'వికేంద్రీకృతం — 16 మండల IFCలు + ఆన్‌లైన్ (అక్టోబర్ 2025 నుండి)',
  'Automated registration ID via SMS + email': 'SMS + ఇమెయిల్ ద్వారా స్వయంచాలక నమోదు ID',
  'Paper receipt only if asked for initially': 'మొదట అడిగితే మాత్రమే కాగితపు రసీదు',
  'Receipt only if asked': 'అడిగితే మాత్రమే రసీదు',
  'Automated, dated, with grievance ID': 'స్వయంచాలకం, తేదీతో, ఫిర్యాదు IDతో',
  'Online — citizens can track status updates': 'ఆన్‌లైన్ — పౌరులు స్థితి నవీకరణలను ట్రాక్ చేయవచ్చు',
  'Online but conditional — ATRs visible only after SNO review': 'ఆన్‌లైన్ కానీ షరతులతో — SNO సమీక్ష తర్వాత మాత్రమే ATRలు కనిపిస్తాయి',
  'Online tracking available': 'ఆన్‌లైన్ ట్రాకింగ్ అందుబాటులో ఉంది',
  'Online tracking + ATR download (Telugu / English)': 'ఆన్‌లైన్ ట్రాకింగ్ + ATR డౌన్‌లోడ్ (తెలుగు / ఇంగ్లీష్)',
  'No public hearing; in-person filing only': 'బహిరంగ విచారణ లేదు; ప్రత్యక్ష దాఖలు మాత్రమే',
  'Hearing at filing — usually redirected to district officer': 'దాఖలు సమయంలో విచారణ — సాధారణంగా జిల్లా అధికారికి మళ్లిస్తారు',
  'Hearing at registration': 'నమోదు సమయంలో విచారణ',
  'Monthly mandal hearings → weekly Mandal Prajavani': 'నెలవారీ మండల విచారణలు → వారపు మండల ప్రజావాణి',
  '21 days (per SOP)': '21 రోజులు (SOP ప్రకారం)',
  'No standard': 'ప్రామాణికం లేదు',
  '30 days (mandatory)': '30 రోజులు (తప్పనిసరి)',
  'No': 'లేదు',
  'None': 'ఏదీ లేదు',
  '17 SOPs notified by Line Departments': 'లైన్ శాఖలు నోటిఫై చేసిన 17 SOPలు',
  'Yes — built into system': 'అవును — వ్యవస్థలో నిర్మించబడింది',
  'Not yet built; pending in software': 'ఇంకా నిర్మించలేదు; సాఫ్ట్‌వేర్‌లో పెండింగ్',
  'Yes — poor rating triggers appeal': 'అవును — తక్కువ రేటింగ్ అప్పీలును ప్రేరేపిస్తుంది',
  'Collector Appeal (pilot module pending)': 'కలెక్టర్ అప్పీలు (పైలట్ మాడ్యూల్ పెండింగ్)',
  'Real-time dashboard + monthly reports': 'రియల్-టైం డాష్‌బోర్డ్ + నెలవారీ నివేదికలు',
  'Civil society review published; portal data partial': 'పౌర సమాజ సమీక్ష ప్రచురించబడింది; పోర్టల్ డేటా పాక్షికం',
  'SSAAT + civil society field follow-up of every case': 'ప్రతి కేసుకు SSAAT + పౌర సమాజ క్షేత్ర ఫాలో-అప్',

  // ─── SECTION 3: OTHER STATES — insights ────────────────────────────────
  'A national pattern': 'ఒక జాతీయ నమూనా',
  'CPGRAMS — the Union Government’s portal launched in 2007 — has grown over 10× in a decade: from ~2 lakh grievances in 2014 to over 29 lakh in 2024. Two-thirds concern central ministries; one-third state-level issues.': 'CPGRAMS — 2007లో ప్రారంభమైన కేంద్ర ప్రభుత్వ పోర్టల్ — ఒక దశాబ్దంలో 10× పెరిగింది: 2014లో ~2 లక్షల ఫిర్యాదుల నుండి 2024లో 29 లక్షలకు పైగా. మూడింట రెండు వంతులు కేంద్ర మంత్రిత్వ శాఖలకు సంబంధించినవి; మూడింట ఒక వంతు రాష్ట్ర-స్థాయి సమస్యలు.',
  'Volume vs intensity': 'పరిమాణం వర్సెస్ తీవ్రత',
  'Madhya Pradesh leads in engagement intensity at 681 grievances per 10,000 population, even though Uttar Pradesh has higher absolute volume (74 lakh annually). Telangana sits at the low end of intensity — suggesting suppressed demand, not absence of grievances.': 'ఉత్తరప్రదేశ్‌లో సంపూర్ణ పరిమాణం ఎక్కువగా (ఏటా 74 లక్షలు) ఉన్నప్పటికీ, 10,000 జనాభాకు 681 ఫిర్యాదులతో మధ్యప్రదేశ్ నిమగ్నత తీవ్రతలో ముందుంది. తెలంగాణ తీవ్రతలో దిగువ స్థాయిలో ఉంది — ఇది ఫిర్యాదులు లేకపోవడం కాదు, అణచివేయబడిన డిమాండ్‌ను సూచిస్తుంది.',
  'Statutes are rare': 'చట్టాలు అరుదు',
  'Only Rajasthan (2012), Bihar (2015), and Meghalaya (2020) have enacted statutory frameworks recognising grievance registration as a legal right. Most systems run on executive mandate alone — leaving the "right to redress" at administrative discretion.': 'రాజస్థాన్ (2012), బీహార్ (2015), మరియు మేఘాలయ (2020) మాత్రమే ఫిర్యాదు నమోదును చట్టపరమైన హక్కుగా గుర్తించే చట్టబద్ధ నిర్మాణాలను రూపొందించాయి. చాలా వ్యవస్థలు కార్యనిర్వాహక ఆదేశంపై మాత్రమే నడుస్తాయి — "పరిష్కార హక్కు"ను పరిపాలనా విచక్షణకు వదిలివేస్తాయి.',
  'RTPS is not GR': 'RTPS అంటే ఫిర్యాదు పరిష్కారం కాదు',
  'By 2026, 24 states have enacted Right to Public Services laws covering routine service delivery (licences, certificates, permits). RTPS standardises transactions but lacks independent appellate structures or means for substantive grievance redress.': '2026 నాటికి, 24 రాష్ట్రాలు సాధారణ సేవా బట్వాడాను (లైసెన్సులు, ధృవీకరణ పత్రాలు, అనుమతులు) కవర్ చేసే పౌర సేవల హక్కు చట్టాలను రూపొందించాయి. RTPS లావాదేవీలను ప్రామాణీకరిస్తుంది కానీ స్వతంత్ర అప్పీలు నిర్మాణాలు లేదా గణనీయమైన ఫిర్యాదు పరిష్కార సాధనాలు లేవు.',
  'CM-branded portals': 'సీఎం-బ్రాండ్ పోర్టల్‌లు',
  'A consistent shift across states: portals are branded with the Chief Minister’s office to signal direct executive accountability — Haryana’s CM Window, MP’s CM Helpline, WB’s Sorasori Mukhyomontri. Branding promises accountability the architecture often does not deliver.': 'రాష్ట్రాలన్నిటిలో స్థిరమైన మార్పు: ప్రత్యక్ష కార్యనిర్వాహక జవాబుదారీతనాన్ని సూచించడానికి పోర్టల్‌లు ముఖ్యమంత్రి కార్యాలయంతో బ్రాండ్ చేయబడ్డాయి — హర్యానా సీఎం విండో, మధ్యప్రదేశ్ సీఎం హెల్ప్‌లైన్, పశ్చిమ బెంగాల్ సొరాసొరి ముఖ్యమంత్రి. బ్రాండింగ్ హామీ ఇచ్చే జవాబుదారీతనాన్ని నిర్మాణం తరచుగా అందించదు.',
  'Police consistently top complaints': 'ఫిర్యాదుల్లో పోలీసు శాఖ స్థిరంగా అగ్రస్థానంలో',
  'Across most states, 10–12 departments account for over 70% of complaints. The Police department frequently ranks in the top recipients — indicating digital portals function as an escalation route for police inaction.': 'చాలా రాష్ట్రాలలో, 10–12 శాఖలు 70% కంటే ఎక్కువ ఫిర్యాదులకు కారణం. పోలీసు శాఖ తరచుగా అగ్ర స్వీకర్తలలో ఉంటుంది — డిజిటల్ పోర్టల్‌లు పోలీసు నిష్క్రియత్వానికి ఎస్కలేషన్ మార్గంగా పనిచేస్తాయని సూచిస్తుంది.',

  'State grievance volumes (annual)': 'రాష్ట్రాల ఫిర్యాదు పరిమాణాలు (వార్షికం)',
  'Source: state portal dashboards, 2024–25': 'మూలం: రాష్ట్ర పోర్టల్ డాష్‌బోర్డులు, 2024–25',

  // ─── SECTION 4: PILOT JOURNEY — timeline events ────────────────────────
  'Public hearing in Hyderabad on access to information and grievance redress. 200+ activists, academics, civil society participate. Twenty testimonies presented; eight resolutions agreed.': 'సమాచార ప్రాప్తి మరియు ఫిర్యాదు పరిష్కారంపై హైదరాబాద్‌లో బహిరంగ విచారణ. 200+ కార్యకర్తలు, విద్యావేత్తలు, పౌర సమాజం పాల్గొన్నారు. ఇరవై సాక్ష్యాలు సమర్పించబడ్డాయి; ఎనిమిది తీర్మానాలు ఆమోదించబడ్డాయి.',
  'Over 20 design meetings between civil society partners, district administration, and CGG to design Pilot architecture.': 'పైలట్ నిర్మాణాన్ని రూపొందించడానికి పౌర సమాజ భాగస్వాములు, జిల్లా పరిపాలన, మరియు CGG మధ్య 20కి పైగా రూపకల్పన సమావేశాలు.',
  'Adilabad Pilot formally launched. IFCs operational across 16 mandals. 90+ GROs designated across 9 line departments.': 'ఆదిలాబాద్ పైలట్ అధికారికంగా ప్రారంభమైంది. 16 మండలాల్లో IFCలు పనిచేస్తున్నాయి. 9 లైన్ శాఖల్లో 90+ GROలు నియమించబడ్డారు.',
  'First round of public hearings — 16 hearings over 9 days. 2,000+ grievances filed; 1,000+ cumulative attendance, peaking at 208 in one session.': 'మొదటి విడత బహిరంగ విచారణలు — 9 రోజుల్లో 16 విచారణలు. 2,000+ ఫిర్యాదులు దాఖలయ్యాయి; 1,000+ మొత్తం హాజరు, ఒక సెషన్‌లో గరిష్ఠంగా 208.',
  'Custom IT system built by civil society to document field follow-up for each grievance.': 'ప్రతి ఫిర్యాదుకు క్షేత్ర ఫాలో-అప్‌ను నమోదు చేయడానికి పౌర సమాజం నిర్మించిన ప్రత్యేక IT వ్యవస్థ.',
  'First Collector Appeal held on 12 September — 49 grievances from 4 mandals. Only one such appeal hearing held during the Pilot.': 'మొదటి కలెక్టర్ అప్పీలు సెప్టెంబర్ 12న జరిగింది — 4 మండలాల నుండి 49 ఫిర్యాదులు. పైలట్ సమయంలో ఇటువంటి ఒక్క అప్పీలు విచారణ మాత్రమే జరిగింది.',
  'Digital portal opened to citizens for direct filing. ATR download enabled. Formal request submitted to SNO Prajavani for four key portal changes.': 'ప్రత్యక్ష దాఖలు కోసం డిజిటల్ పోర్టల్ పౌరులకు తెరవబడింది. ATR డౌన్‌లోడ్ ప్రారంభించబడింది. నాలుగు కీలక పోర్టల్ మార్పుల కోసం SNO ప్రజావాణికి అధికారిక అభ్యర్థన సమర్పించబడింది.',
  'Weekly Mandal Prajavani institutionalised — every Monday at MPDO offices. The Pilot’s most notable institutional outcome.': 'వారపు మండల ప్రజావాణి సంస్థాగతీకరించబడింది — ప్రతి సోమవారం MPDO కార్యాలయాల్లో. పైలట్ యొక్క అత్యంత గుర్తించదగిన సంస్థాగత ఫలితం.',
  'Mandal Prajavani formally launched with full feature set: digital registration, dated receipts, written GRO remarks, online upload before exit.': 'మండల ప్రజావాణి పూర్తి ఫీచర్లతో అధికారికంగా ప్రారంభమైంది: డిజిటల్ నమోదు, తేదీగల రసీదులు, వ్రాతపూర్వక GRO వ్యాఖ్యలు, నిష్క్రమణకు ముందు ఆన్‌లైన్ అప్‌లోడ్.',
  'Government Order issued: institutionalising, decentralising and integrating the Prajavani mechanism across Telangana.': 'ప్రభుత్వ ఉత్తర్వు జారీ: తెలంగాణ అంతటా ప్రజావాణి యంత్రాంగాన్ని సంస్థాగతీకరించడం, వికేంద్రీకరించడం మరియు సమైక్యం చేయడం.',

  'Mandals covered': 'కవర్ చేసిన మండలాలు',
  'GROs across 9 line departments': '9 లైన్ శాఖల్లో GROలు',
  'Civil society volunteers from across India': 'భారతదేశం అంతటి నుండి పౌర సమాజ వాలంటీర్లు',
  'Notified SOPs by line departments': 'లైన్ శాఖలు నోటిఫై చేసిన SOPలు',
  'Grievance categories': 'ఫిర్యాదు వర్గాలు',
  'Departments with grievance volume': 'ఫిర్యాదు పరిమాణం గల శాఖలు',

  // ─── SECTION 5: HOW THE MODEL WORKS ────────────────────────────────────
  'Details →': 'వివరాలు →',
  'Independent verification by SSAAT + civil society wraps around every step': 'ప్రతి దశ చుట్టూ SSAAT + పౌర సమాజం స్వతంత్ర సత్యాపన ఉంటుంది',
  'Village outreach': 'గ్రామ సంప్రదింపు',
  'IFC filing': 'IFC దాఖలు',
  'GRO inquiry': 'GRO విచారణ',
  'Mandal Prajavani': 'మండల ప్రజావాణి',
  'Written ATR': 'వ్రాతపూర్వక ATR',
  'Collector Appeal': 'కలెక్టర్ అప్పీలు',

  // IFC
  'Information Facilitation Centre': 'సమాచార సదుపాయ కేంద్రం',
  'A dedicated data-entry desk at each mandal office, staffed by an operator who registers grievances and issues acknowledgement receipts.': 'ప్రతి మండల కార్యాలయంలో ఒక ప్రత్యేక డేటా-ఎంట్రీ డెస్క్ — ఫిర్యాదులను నమోదు చేసి స్వీకృతి రసీదులు జారీ చేసే ఆపరేటర్‌తో.',
  'Mandal-level access point': 'మండల-స్థాయి ప్రాప్తి కేంద్రం',
  '16 IFCs were established across 16 mandals, operational 9 am to 5 pm on all working days. The IFC reduces travel cost — citizens no longer need to travel to Hyderabad — but the Pilot also revealed that mandal-level was not enough: most grievances were filed at village/panchayat level with SSAAT and civil society support.': '16 మండలాల్లో 16 IFCలు ఏర్పాటు చేయబడ్డాయి, పని దినాల్లో ఉదయం 9 నుండి సాయంత్రం 5 వరకు పనిచేస్తాయి. IFC ప్రయాణ ఖర్చును తగ్గిస్తుంది — పౌరులు ఇక హైదరాబాద్‌కు ప్రయాణించాల్సిన అవసరం లేదు — కానీ మండల-స్థాయి సరిపోదని పైలట్ వెల్లడించింది: చాలా ఫిర్యాదులు SSAAT మరియు పౌర సమాజ మద్దతుతో గ్రామ/పంచాయితీ స్థాయిలో దాఖలయ్యాయి.',
  'Activities at an IFC': 'IFCలో కార్యకలాపాలు',
  'Register grievances across all 20 Pilot categories on the Prajavani-CGG portal': 'ప్రజావాణి-CGG పోర్టల్‌లో మొత్తం 20 పైలట్ వర్గాల్లో ఫిర్యాదులను నమోదు చేయడం',
  'Issue a dated, printed acknowledgement receipt to the complainant': 'ఫిర్యాదుదారునికి తేదీగల, ముద్రిత స్వీకృతి రసీదు జారీ చేయడం',
  'Provide proactive information about scheme eligibility (Mahalaxmi, Gruhajyothi, MGNREGA, etc.)': 'పథక అర్హత గురించి చురుకైన సమాచారం అందించడం (మహాలక్ష్మి, గృహజ్యోతి, MGNREGA, తదితర)',
  'Verify identity documents and ration card details where required': 'అవసరమైన చోట గుర్తింపు పత్రాలు మరియు రేషన్ కార్డు వివరాలను ధృవీకరించడం',
  'Assist with status tracking and ATR access once portal opened to public (Oct 2025)': 'పోర్టల్ ప్రజలకు తెరిచిన తర్వాత (అక్టోబర్ 2025) స్థితి ట్రాకింగ్ మరియు ATR ప్రాప్తికి సహాయం చేయడం',
  'Gap revealed by the Pilot': 'పైలట్ వెల్లడించిన లోపం',
  'IFC at mandal level still required travel for many citizens': 'మండల స్థాయిలోని IFC ఇంకా చాలామంది పౌరులకు ప్రయాణం అవసరం చేసింది',
  'Most grievances came via SSAAT + civil society outreach at panchayat level': 'చాలా ఫిర్యాదులు పంచాయితీ స్థాయిలో SSAAT + పౌర సమాజ సంప్రదింపు ద్వారా వచ్చాయి',
  'Way Forward: IFCs should be made more accessible to local communities — at panchayat or village level': 'ముందుకు దారి: IFCలను స్థానిక సమాజాలకు మరింత అందుబాటులో ఉంచాలి — పంచాయితీ లేదా గ్రామ స్థాయిలో',

  // PDI
  'Proactive Disclosure of Information': 'సమాచారం యొక్క చురుకైన వెల్లడి',
  'Proactive disclosure of information about government programmes — pensions, ration cards, farmer subsidies — so citizens understand their entitlements and can file informed grievances.': 'ప్రభుత్వ కార్యక్రమాల గురించి — పెన్షన్లు, రేషన్ కార్డులు, రైతు సబ్సిడీలు — చురుకైన సమాచార వెల్లడి, తద్వారా పౌరులు తమ హక్కులను అర్థం చేసుకుని సమాచారయుక్త ఫిర్యాదులు దాఖలు చేయగలరు.',
  'Information as the first step to redress': 'పరిష్కారానికి మొదటి అడుగు సమాచారం',
  'A key component of the model is the proactive disclosure of information about government programmes — social security pensions, ration cards, farmer subsidies and similar schemes. Access to clear information improves citizens’ understanding of various government initiatives, helps them diagnose problems with their own applications, and enables them to file informed grievances that seek the appropriate intervention.': 'నమూనా యొక్క ఒక కీలక భాగం ప్రభుత్వ కార్యక్రమాల గురించి — సామాజిక భద్రతా పెన్షన్లు, రేషన్ కార్డులు, రైతు సబ్సిడీలు మరియు సారూప్య పథకాల గురించి — చురుకైన సమాచార వెల్లడి. స్పష్టమైన సమాచార ప్రాప్తి పౌరులకు వివిధ ప్రభుత్వ కార్యక్రమాలపై అవగాహనను పెంచుతుంది, వారి స్వంత దరఖాస్తుల్లోని సమస్యలను నిర్ధారించడంలో సహాయపడుతుంది, మరియు తగిన జోక్యాన్ని కోరే సమాచారయుక్త ఫిర్యాదులు దాఖలు చేయడానికి వీలు కల్పిస్తుంది.',
  'Why proactive disclosure matters': 'చురుకైన వెల్లడి ఎందుకు ముఖ్యం',
  'Many citizens do not file grievances simply because they are unaware of their entitlements, or of why an application was rejected': 'చాలామంది పౌరులు తమ హక్కుల గురించి, లేదా దరఖాస్తు ఎందుకు తిరస్కరించబడిందో తెలియక ఫిర్యాదులు దాఖలు చేయరు',
  'Clear information about eligibility and application status lets citizens identify the actual problem before approaching the system': 'అర్హత మరియు దరఖాస్తు స్థితి గురించి స్పష్టమైన సమాచారం వ్యవస్థను సంప్రదించే ముందే వాస్తవ సమస్యను గుర్తించడానికి పౌరులకు వీలు కల్పిస్తుంది',
  'Informed grievances are better defined, easier for GROs to act on, and quicker to resolve': 'సమాచారయుక్త ఫిర్యాదులు మరింత స్పష్టంగా ఉంటాయి, GROలకు చర్య తీసుకోవడం సులభం, మరియు పరిష్కారం వేగవంతం',
  'How it featured in the Pilot': 'పైలట్‌లో ఇది ఎలా కనిపించింది',
  'IFC operators and civil society volunteers shared scheme eligibility information while registering grievances': 'IFC ఆపరేటర్లు మరియు పౌర సమాజ వాలంటీర్లు ఫిర్యాదులు నమోదు చేస్తూ పథక అర్హత సమాచారాన్ని పంచుకున్నారు',
  'Information was actively carried to the village level — not left passively available online': 'సమాచారం గ్రామ స్థాయికి చురుకుగా తీసుకెళ్లబడింది — కేవలం ఆన్‌లైన్‌లో నిష్క్రియంగా వదిలివేయలేదు',
  'Way Forward: a dedicated proactive disclosure system (Praja Soochana) should sit alongside Prajavani statewide': 'ముందుకు దారి: ఒక అంకిత చురుకైన వెల్లడి వ్యవస్థ (ప్రజా సూచన) రాష్ట్రవ్యాప్తంగా ప్రజావాణి పక్కన ఉండాలి',

  // GRO
  'Grievance Redress Officer': 'ఫిర్యాదు పరిష్కార అధికారి',
  'A mandal-level officer one level above frontline staff — given additional charge of investigating and responding to grievances within their department.': 'ముందువరుస సిబ్బంది కంటే ఒక స్థాయి పైన ఉండే మండల-స్థాయి అధికారి — తమ శాఖలో ఫిర్యాదులను విచారించి స్పందించే అదనపు బాధ్యత అప్పగించబడిన వారు.',
  'Designated authority for adjudication': 'తీర్పు కోసం నిర్దేశిత అధికారి',
  'In an ideal system, the GRO would be independent of the implementing authority — but this was not practically feasible across all line departments. The Pilot designated officers one level higher than frontline staff: 90+ GROs across 9 line departments, all given orientation on Pilot modalities.': 'ఆదర్శ వ్యవస్థలో, GRO అమలు చేసే అధికారి నుండి స్వతంత్రంగా ఉండాలి — కానీ ఇది అన్ని లైన్ శాఖల్లో ఆచరణాత్మకంగా సాధ్యం కాలేదు. పైలట్ ముందువరుస సిబ్బంది కంటే ఒక స్థాయి పైన అధికారులను నియమించింది: 9 లైన్ శాఖల్లో 90+ GROలు, అందరికీ పైలట్ విధానాలపై శిక్షణ ఇవ్వబడింది.',
  'Department-wise GRO designation': 'శాఖల వారీగా GRO నియామకం',
  'Agriculture → Mandal Agricultural Officer (MAO)': 'వ్యవసాయం → మండల వ్యవసాయ అధికారి (MAO)',
  'Revenue → Tahsildar / Mandal Revenue Officer (MRO)': 'రెవెన్యూ → తహసీల్దార్ / మండల రెవెన్యూ అధికారి (MRO)',
  'Energy → Assistant Engineer (AE), Electricity Department': 'విద్యుత్ → సహాయ ఇంజనీర్ (AE), విద్యుత్ శాఖ',
  'Panchayat Raj & RD → Mandal Parishad Development Officer (MPDO)': 'పంచాయితీ రాజ్ & RD → మండల పరిషత్ అభివృద్ధి అధికారి (MPDO)',
  'Food & Civil Supplies → Ration Card: Tahsildar / MRO · Gas Subsidy: MPDO': 'ఆహార & పౌర సరఫరా → రేషన్ కార్డు: తహసీల్దార్ / MRO · గ్యాస్ సబ్సిడీ: MPDO',
  'Tribal Welfare → Deputy Director, ITDA (Forest Rights)': 'గిరిజన సంక్షేమం → డిప్యూటీ డైరెక్టర్, ITDA (అటవీ హక్కులు)',
  'Housing → Housing officer, Mandal level': 'గృహ నిర్మాణం → గృహ నిర్మాణ అధికారి, మండల స్థాయి',
  'GRO responsibilities under Pilot SOPs': 'పైలట్ SOPల కింద GRO బాధ్యతలు',
  'Conduct enquiry into the grievances marked to them, including conducting field verification, in line with the SOPs': 'SOPలకు అనుగుణంగా, క్షేత్ర సత్యాపనతో సహా, తమకు మార్క్ చేయబడిన ఫిర్యాదులపై విచారణ నిర్వహించడం',
  'File a written ATR with specific action remarks within 30 days': '30 రోజులలోపు నిర్దిష్ట చర్య వ్యాఖ్యలతో వ్రాతపూర్వక ATR దాఖలు చేయడం',
  'Attend Mandal Prajavanis and share enquiry findings; record remarks on pre-formatted receipt in writing': 'మండల ప్రజావాణులకు హాజరై విచారణ ఫలితాలను పంచుకోవడం; ముందుగా-రూపొందించిన రసీదుపై వ్యాఖ్యలను వ్రాతలో నమోదు చేయడం',
  'Respond to Collector Appeal if the case is escalated': 'కేసు ఎస్కలేట్ అయితే కలెక్టర్ అప్పీలుకు స్పందించడం',
  'Observed limitations': 'గమనించిన పరిమితులు',
  'Several GROs continued to show lack of ownership over the system': 'చాలామంది GROలు వ్యవస్థపై యాజమాన్య భావం లేకపోవడాన్ని కొనసాగించారు',
  'Repeated training is required, including in-person rounds — currently uneven across mandals': 'పునరావృత శిక్షణ అవసరం, ప్రత్యక్ష రౌండ్లతో సహా — ప్రస్తుతం మండలాల మధ్య అసమానంగా ఉంది',

  // SOP
  'Standard Operating Procedures': 'ప్రామాణిక ఆపరేటింగ్ ప్రొసీజర్‌లు',
  '17 SOPs issued by the respective line departments — specifying exactly what action a GRO must take for each grievance category.': 'సంబంధిత లైన్ శాఖలు జారీ చేసిన 17 SOPలు — ప్రతి ఫిర్యాదు వర్గానికి GRO ఏ చర్య తీసుకోవాలో ఖచ్చితంగా నిర్దేశిస్తాయి.',
  'Converting discretion into procedure': 'విచక్షణను ప్రక్రియగా మార్చడం',
  'SOPs proved one of the Pilot’s most valuable design choices. They enabled reasoned, time-bound action by officers without passing the burden back onto citizens. During hearings, GROs frequently referenced SOPs — and citizens received clearer written commitments as a result.': 'SOPలు పైలట్ యొక్క అత్యంత విలువైన రూపకల్పన ఎంపికలలో ఒకటిగా రుజువయ్యాయి. భారాన్ని తిరిగి పౌరులపై వేయకుండా అధికారులు తర్కబద్ధమైన, సమయ-బద్ధ చర్య తీసుకోవడానికి అవి వీలు కల్పించాయి. విచారణల సమయంలో, GROలు తరచుగా SOPలను సూచించారు — ఫలితంగా పౌరులు మరింత స్పష్టమైన వ్రాతపూర్వక హామీలను అందుకున్నారు.',
  'Why SOPs matter': 'SOPలు ఎందుకు ముఖ్యం',
  'Specify the minimum steps the GRO must take before filing an ATR': 'ATR దాఖలు చేసే ముందు GRO తీసుకోవాల్సిన కనీస దశలను నిర్దేశించడం',
  'Set clear expectations for the citizen about what will happen': 'ఏమి జరుగుతుందో పౌరునికి స్పష్టమైన అంచనాలను ఏర్పరచడం',
  'Make ATR quality comparable across mandals and departments': 'మండలాలు మరియు శాఖల మధ్య ATR నాణ్యతను పోల్చదగినదిగా చేయడం',
  'Reduce arbitrariness — responses follow category, not individual discretion': 'ఏకపక్షతను తగ్గించడం — స్పందనలు వ్యక్తిగత విచక్షణ కాదు, వర్గాన్ని అనుసరిస్తాయి',
  'Help GROs justify decisions where the issue is state-level or policy-bound': 'సమస్య రాష్ట్ర-స్థాయి లేదా విధాన-బద్ధమైనప్పుడు నిర్ణయాలను సమర్థించడంలో GROలకు సహాయం',
  'Departments with SOPs issued': 'SOPలు జారీ చేసిన శాఖలు',
  'Panchayat Raj & RD — MGNREGA, Pensions': 'పంచాయితీ రాజ్ & RD — MGNREGA, పెన్షన్లు',
  'Food & Civil Supplies — Gas Subsidy, Ration Card': 'ఆహార & పౌర సరఫరా — గ్యాస్ సబ్సిడీ, రేషన్ కార్డు',
  'Energy — Gruhajyothi, Service Issues, Electrocution Death': 'విద్యుత్ — గృహజ్యోతి, సేవా సమస్యలు, విద్యుదాఘాత మరణం',
  'Revenue — Land Issues, Survey, Certificates': 'రెవెన్యూ — భూమి సమస్యలు, సర్వే, ధృవీకరణ పత్రాలు',
  'Agriculture — PM Kisan, Crop Loan Waiver, Rythu Bima': 'వ్యవసాయం — పీఎం కిసాన్, పంట రుణ మాఫీ, రైతు బీమా',
  'Tribal Welfare — Individual Forest Rights (IFR)': 'గిరిజన సంక్షేమం — వ్యక్తిగత అటవీ హక్కులు (IFR)',
  'Recommendation': 'సిఫారసు',
  'SOPs must be regularly updated in consultation with mandal- and district-level officials': 'మండల- మరియు జిల్లా-స్థాయి అధికారులతో సంప్రదించి SOPలను క్రమం తప్పకుండా నవీకరించాలి',
  'Updates must reflect both local issues and state-level policy changes': 'నవీకరణలు స్థానిక సమస్యలు మరియు రాష్ట్ర-స్థాయి విధాన మార్పులు రెండింటిని ప్రతిబింబించాలి',
  'Way Forward: All line departments statewide should issue SOPs for grievances pertaining to their schemes': 'ముందుకు దారి: రాష్ట్రవ్యాప్తంగా అన్ని లైన్ శాఖలు తమ పథకాలకు సంబంధించిన ఫిర్యాదుల కోసం SOPలను జారీ చేయాలి',

  // PH
  'Public Hearing / Mandal Prajavani': 'బహిరంగ విచారణ / మండల ప్రజావాణి',
  'Open public platform where citizens and GROs meet face to face. Initially monthly; institutionalised as weekly Mandal Prajavani every Monday from November 2025.': 'పౌరులు మరియు GROలు ముఖాముఖి కలుసుకునే బహిరంగ వేదిక. మొదట నెలవారీ; నవంబర్ 2025 నుండి ప్రతి సోమవారం వారపు మండల ప్రజావాణిగా సంస్థాగతీకరించబడింది.',
  'The Pilot’s most effective feature': 'పైలట్ యొక్క అత్యంత ప్రభావవంతమైన లక్షణం',
  'Five rounds of public hearings (80+ hearings) were held at the mandal level in the first year. Each public hearing was presided over by a district-level officer, with all mandal-level officers present and open for the public to attend. The space was organised with a series of desks to manage the flow of proceedings: an Entry Desk to issue tokens to complainants (for registered grievances), the Presiding Officer’s Desk, various GROs’ Desks (department-wise), an Exit Desk to record officers’ responses before the citizen left, and a separate IFC Desk for filing new grievances.': 'మొదటి సంవత్సరంలో మండల స్థాయిలో ఐదు విడతల బహిరంగ విచారణలు (80+ విచారణలు) జరిగాయి. ప్రతి బహిరంగ విచారణకు ఒక జిల్లా-స్థాయి అధికారి అధ్యక్షత వహించారు, అన్ని మండల-స్థాయి అధికారులు హాజరై, ప్రజలు హాజరయ్యేందుకు తెరిచి ఉంచారు. కార్యకలాపాల ప్రవాహాన్ని నిర్వహించడానికి ఆ స్థలం వరుస డెస్క్‌లతో ఏర్పాటు చేయబడింది: ఫిర్యాదుదారులకు టోకెన్లు జారీ చేసే ప్రవేశ డెస్క్ (నమోదైన ఫిర్యాదుల కోసం), అధ్యక్ష అధికారి డెస్క్, వివిధ GROల డెస్క్‌లు (శాఖల వారీగా), పౌరుడు వెళ్లే ముందు అధికారుల స్పందనలను నమోదు చేసే నిష్క్రమణ డెస్క్, మరియు కొత్త ఫిర్యాదులు దాఖలు చేయడానికి ఒక ప్రత్యేక IFC డెస్క్.',
  'What was achieved at hearings': 'విచారణలలో ఏమి సాధించబడింది',
  'Agriculture Department officials acknowledged errors in crop loan waiver records — agreed to write to concerned banks': 'వ్యవసాయ శాఖ అధికారులు పంట రుణ మాఫీ రికార్డులలో తప్పులను అంగీకరించారు — సంబంధిత బ్యాంకులకు వ్రాయడానికి అంగీకరించారు',
  'Rural Development officials followed up on pensions withheld at the State level for years': 'గ్రామీణాభివృద్ధి అధికారులు సంవత్సరాలుగా రాష్ట్ర స్థాయిలో నిలిపివేసిన పెన్షన్లపై ఫాలో-అప్ చేశారు',
  'Data mismatches across Aadhaar, ration cards, and LPG records were corrected on the spot at dedicated desks': 'ఆధార్, రేషన్ కార్డులు, మరియు LPG రికార్డుల మధ్య డేటా అసమతుల్యతలు అంకిత డెస్క్‌ల వద్ద అక్కడికక్కడే సరిచేయబడ్డాయి',
  'Pension restorations confirmed in writing; urgent decisions taken immediately': 'పెన్షన్ పునరుద్ధరణలు వ్రాతలో నిర్ధారించబడ్డాయి; అత్యవసర నిర్ణయాలు వెంటనే తీసుకోబడ్డాయి',
  'Inter-departmental coordination — gas agencies, MeeSeva centres also attended and processed applications': 'అంతర-శాఖా సమన్వయం — గ్యాస్ ఏజెన్సీలు, మీసేవ కేంద్రాలు కూడా హాజరై దరఖాస్తులను ప్రాసెస్ చేశాయి',
  'Friction encountered during the Pilot': 'పైలట్ సమయంలో ఎదురైన ఇబ్బందులు',
  'Scheduling monthly hearings required repeated follow-up — officers prioritised other administrative work': 'నెలవారీ విచారణల షెడ్యూలింగ్‌కు పునరావృత ఫాలో-అప్ అవసరమైంది — అధికారులు ఇతర పరిపాలనా పనికి ప్రాధాన్యత ఇచ్చారు',
  'Only 5 rounds in 10 months — leading to the shift to weekly Mandal Prajavani': '10 నెలల్లో కేవలం 5 విడతలు — వారపు మండల ప్రజావాణికి మారడానికి దారితీసింది',
  'In Gondi-speaking areas, citizens often did not follow Telugu proceedings beyond their own case': 'గోండి మాట్లాడే ప్రాంతాల్లో, పౌరులు తరచుగా తమ సొంత కేసు తప్ప తెలుగు కార్యకలాపాలను అనుసరించలేకపోయారు',
  'Lack of drinking water and accessible toilets in some mandal offices — particularly hard on women petitioners': 'కొన్ని మండల కార్యాలయాల్లో తాగునీరు మరియు అందుబాటు మరుగుదొడ్ల కొరత — ముఖ్యంగా మహిళా దరఖాస్తుదారులకు కష్టం',
  'When the Collector was present, hearings were more orderly; otherwise discipline degraded as sessions ran into late afternoon': 'కలెక్టర్ ఉన్నప్పుడు, విచారణలు మరింత క్రమబద్ధంగా ఉన్నాయి; లేకపోతే సెషన్లు మధ్యాహ్నం ఆలస్యంగా సాగేకొద్దీ క్రమశిక్షణ క్షీణించింది',
  'November 2025 — weekly Mandal Prajavani': 'నవంబర్ 2025 — వారపు మండల ప్రజావాణి',
  'Every Monday at MPDO office; all concerned mandal-level officers present': 'ప్రతి సోమవారం MPDO కార్యాలయంలో; సంబంధిత అన్ని మండల-స్థాయి అధికారులు హాజరు',
  'IFC operators register grievances; citizens receive pre-formatted receipts': 'IFC ఆపరేటర్లు ఫిర్యాదులను నమోదు చేస్తారు; పౌరులు ముందుగా-రూపొందించిన రసీదులు అందుకుంటారు',
  'GRO’s remarks recorded on receipt in writing during the session': 'సెషన్ సమయంలో GRO వ్యాఖ్యలు రసీదుపై వ్రాతలో నమోదు చేయబడతాయి',
  'Remarks uploaded to portal before exit': 'నిష్క్రమణకు ముందు వ్యాఖ్యలు పోర్టల్‌కు అప్‌లోడ్ చేయబడతాయి',
  'Operates at minimal additional cost by repurposing existing mandal infrastructure': 'ఇప్పటికే ఉన్న మండల మౌలిక సదుపాయాలను తిరిగి ఉపయోగించడం ద్వారా కనీస అదనపు ఖర్చుతో పనిచేస్తుంది',

  // ATR
  'Action Taken Report': 'చర్య తీసుకున్న నివేదిక (ATR)',
  'Mandatory written response from the GRO within 30 days. Available online (Oct 2025+) and downloadable by the citizen.': '30 రోజులలోపు GRO నుండి తప్పనిసరి వ్రాతపూర్వక స్పందన. ఆన్‌లైన్‌లో అందుబాటులో (అక్టోబర్ 2025+) మరియు పౌరుడు డౌన్‌లోడ్ చేసుకోవచ్చు.',
  'From verbal promise to written record': 'మౌఖిక వాగ్దానం నుండి వ్రాతపూర్వక రికార్డుకు',
  'The ATR was the Pilot’s primary accountability document. By forcing officials to put their response in writing, it transformed cases that would otherwise be evaded. Under MGNREGA, for instance, ATRs stating jobs were on hold "as per instructions of Commissioner RD TS" became written proof of statutory violation.': 'ATR పైలట్ యొక్క ప్రాథమిక జవాబుదారీ పత్రం. అధికారులు తమ స్పందనను వ్రాతలో పెట్టేలా బలవంతం చేయడం ద్వారా, లేకపోతే తప్పించుకునే కేసులను అది మార్చింది. ఉదాహరణకు MGNREGA కింద, "RD TS కమిషనర్ సూచనల ప్రకారం" ఉద్యోగాలు నిలిపివేయబడ్డాయని పేర్కొన్న ATRలు చట్టబద్ధ ఉల్లంఘనకు వ్రాతపూర్వక సాక్ష్యంగా మారాయి.',
  'Pilot ATR statistics': 'పైలట్ ATR గణాంకాలు',
  '7,998 ATRs filed (as of data cut-off)': '7,998 ATRలు దాఖలయ్యాయి (డేటా కట్-ఆఫ్ నాటికి)',
  '30-day timeline mandatory per SOPs': 'SOPల ప్రకారం 30-రోజుల గడువు తప్పనిసరి',
  '520 grievances marked for Collector Appeal because no ATR was filed at all': 'ఏ ATR దాఖలు కాకపోవడం వల్ల 520 ఫిర్యాదులు కలెక్టర్ అప్పీలు కోసం మార్క్ చేయబడ్డాయి',
  '486 additional grievances marked for appeal due to non-compliance with SOP or wrong ATR remarks': 'SOP పాటించకపోవడం లేదా తప్పు ATR వ్యాఖ్యల కారణంగా అదనంగా 486 ఫిర్యాదులు అప్పీలు కోసం మార్క్ చేయబడ్డాయి',
  'Critical gaps identified': 'గుర్తించిన కీలక లోపాలు',
  'System allows only one final ATR per grievance — obscures cases that move through multiple levels': 'వ్యవస్థ ఒక ఫిర్యాదుకు ఒకే తుది ATRను అనుమతిస్తుంది — బహుళ స్థాయుల గుండా వెళ్లే కేసులను అస్పష్టం చేస్తుంది',
  'A mandal officer may file a "final" ATR while case actually requires district / state action': 'కేసుకు వాస్తవానికి జిల్లా / రాష్ట్ర చర్య అవసరమైనప్పటికీ ఒక మండల అధికారి "తుది" ATR దాఖలు చేయవచ్చు',
  'No automatic SMS notification to citizen when ATR is filed (active until Jan 2026; now stopped)': 'ATR దాఖలైనప్పుడు పౌరునికి స్వయంచాలక SMS నోటిఫికేషన్ లేదు (జనవరి 2026 వరకు చురుకుగా; ఇప్పుడు ఆగిపోయింది)',
  'Disposed ≠ Resolved — Pilot moved away from binary "Disposed/Pending" framework to 11-status review': 'పరిష్కరించబడింది ≠ పరిష్కారం — పైలట్ బైనరీ "పరిష్కరించబడింది/పెండింగ్" ఫ్రేమ్‌వర్క్ నుండి 11-స్థితి సమీక్షకు మారింది',
  'Standardisation of remarks': 'వ్యాఖ్యల ప్రామాణీకరణ',
  'Civil society + CGG designed category-specific remark templates after early hearings': 'తొలి విచారణల తర్వాత పౌర సమాజం + CGG వర్గ-నిర్దిష్ట వ్యాఖ్య టెంప్లేట్లను రూపొందించాయి',
  'Separate templates for Pensions, Gas Subsidy, Gruhajyothi, Crop Loan Waiver': 'పెన్షన్లు, గ్యాస్ సబ్సిడీ, గృహజ్యోతి, పంట రుణ మాఫీకి వేర్వేరు టెంప్లేట్లు',
  '3–4 standard options plus an "Other" box per category': 'ప్రతి వర్గానికి 3–4 ప్రామాణిక ఎంపికలు మరియు ఒక "ఇతర" బాక్స్',
  'Result: faster, more consistent officer responses; clearer commitments for citizens': 'ఫలితం: వేగవంతమైన, మరింత స్థిరమైన అధికారి స్పందనలు; పౌరులకు స్పష్టమైన హామీలు',

  // APL
  'Second-tier escalation where the District Collector personally reviews unresolved or non-compliant cases.': 'జిల్లా కలెక్టర్ పరిష్కారం కాని లేదా నిబంధనలకు విరుద్ధమైన కేసులను వ్యక్తిగతంగా సమీక్షించే రెండవ-అంచె ఎస్కలేషన్.',
  'A safeguard for procedural accountability': 'ప్రక్రియాపరమైన జవాబుదారీతనానికి ఒక రక్షణ',
  'Before the Pilot, a local official’s response was effectively final — there was no institutional recourse. The Collector Appeal establishes a rights-based pathway when ATRs are inadequate, non-compliant, or delayed. Of 5,000 reviewed grievances, 1,006 (20%) were marked for appeal.': 'పైలట్ ముందు, స్థానిక అధికారి స్పందన ఆచరణలో తుది నిర్ణయం — ఎటువంటి సంస్థాగత పునరాశ్రయం లేదు. ATRలు సరిపోనప్పుడు, నిబంధనలకు విరుద్ధమైనప్పుడు, లేదా ఆలస్యమైనప్పుడు కలెక్టర్ అప్పీలు ఒక హక్కు-ఆధారిత మార్గాన్ని ఏర్పరుస్తుంది. సమీక్షించిన 5,000 ఫిర్యాదులలో, 1,006 (20%) అప్పీలు కోసం మార్క్ చేయబడ్డాయి.',
  'When a case is marked for appeal': 'కేసు ఎప్పుడు అప్పీలు కోసం మార్క్ చేయబడుతుంది',
  'No ATR has been filed within the 30-day window (520 of the 1,006 appeal cases)': '30-రోజుల వ్యవధిలో ఏ ATR దాఖలు కాలేదు (1,006 అప్పీలు కేసులలో 520)',
  'ATR filed but non-compliant with the SOP': 'ATR దాఖలైంది కానీ SOPకి అనుగుణంగా లేదు',
  'ATR filed but factually inaccurate (revealed via field verification)': 'ATR దాఖలైంది కానీ వాస్తవంగా సరికాదు (క్షేత్ర సత్యాపన ద్వారా వెల్లడైంది)',
  'Specific high-volume issues — e.g. 221 MGNREGA appeals where GROs cited Commissioner’s instructions to hold up new job cards': 'నిర్దిష్ట అధిక-పరిమాణ సమస్యలు — ఉదా. కొత్త జాబ్ కార్డులను నిలిపివేయడానికి GROలు కమిషనర్ సూచనలను ఉదహరించిన 221 MGNREGA అప్పీళ్లు',
  'Pilot appeal proceedings': 'పైలట్ అప్పీలు కార్యకలాపాలు',
  'Only one Collector Appeal hearing held during the Pilot — 12 September 2025': 'పైలట్ సమయంలో ఒకే కలెక్టర్ అప్పీలు విచారణ జరిగింది — 12 సెప్టెంబర్ 2025',
  '49 grievances from Adilabad (Rural), Jainath, Narnoor, and Utnoor mandals': 'ఆదిలాబాద్ (గ్రామీణ), జైనథ్, నార్నూర్, మరియు ఉట్నూర్ మండలాల నుండి 49 ఫిర్యాదులు',
  'Collector presided; district-level officers and GROs attended; tripartite dialogue with complainants': 'కలెక్టర్ అధ్యక్షత వహించారు; జిల్లా-స్థాయి అధికారులు మరియు GROలు హాజరయ్యారు; ఫిర్యాదుదారులతో త్రైపాక్షిక సంభాషణ',
  'Resolved exceptional cases requiring state-level clarification and long-pending issues': 'రాష్ట్ర-స్థాయి స్పష్టత అవసరమైన అసాధారణ కేసులు మరియు దీర్ఘకాలంగా పెండింగ్‌లో ఉన్న సమస్యలు పరిష్కరించబడ్డాయి',
  'Critical gaps': 'కీలక లోపాలు',
  'No dedicated software module for Collector Appeal — was a Pilot software shortfall': 'కలెక్టర్ అప్పీలు కోసం అంకిత సాఫ్ట్‌వేర్ మాడ్యూల్ లేదు — ఇది పైలట్ సాఫ్ట్‌వేర్ లోటు',
  'No auto-escalation when ATRs aren’t filed within 30 days': '30 రోజులలోపు ATRలు దాఖలు కానప్పుడు స్వయంచాలక ఎస్కలేషన్ లేదు',
  'Until Jan 2026 citizens couldn’t file appeals directly — entirely facilitated by SSAAT and civil society': 'జనవరి 2026 వరకు పౌరులు నేరుగా అప్పీళ్లు దాఖలు చేయలేకపోయారు — పూర్తిగా SSAAT మరియు పౌర సమాజం సహాయం చేశాయి',
  'A second appeal hearing could not be scheduled due to various reasons': 'వివిధ కారణాల వల్ల రెండవ అప్పీలు విచారణను షెడ్యూల్ చేయలేకపోయారు',

  // DGT (Digital Platform component)
  'Digital Platform': 'డిజిటల్ ప్లాట్‌ఫార్మ్',
  'The "Adilabad Pilot" tab on prajavani.cgg.gov.in — added after persistent follow-up with the SNO and the Adilabad Collector.': 'prajavani.cgg.gov.inలో "ఆదిలాబాద్ పైలట్" ట్యాబ్ — SNO మరియు ఆదిలాబాద్ కలెక్టర్‌తో నిరంతర ఫాలో-అప్ తర్వాత జోడించబడింది.',
  'Built around the citizen, not the back-end': 'బ్యాక్-ఎండ్ కాదు, పౌరుని చుట్టూ నిర్మించబడింది',
  'The digital platform was developed by CGG in three phases between January 2025 and April 2026. The most important learning: software shapes practice more than instructions do. Regardless of the SOP, officers act on what their login screen prompts them to do.': 'డిజిటల్ ప్లాట్‌ఫార్మ్‌ను CGG జనవరి 2025 మరియు ఏప్రిల్ 2026 మధ్య మూడు దశలలో అభివృద్ధి చేసింది. అత్యంత ముఖ్యమైన అభ్యాసం: సూచనల కంటే సాఫ్ట్‌వేర్ ఆచరణను ఎక్కువగా రూపొందిస్తుంది. SOP ఏమైనప్పటికీ, అధికారులు తమ లాగిన్ స్క్రీన్ సూచించిన దాని ప్రకారం చర్య తీసుకుంటారు.',
  'Features built into the portal': 'పోర్టల్‌లో నిర్మించిన లక్షణాలు',
  'Mobile-OTP filing — no in-person visit to Hyderabad required': 'మొబైల్-OTP దాఖలు — హైదరాబాద్‌కు ప్రత్యక్ష సందర్శన అవసరం లేదు',
  'Status tracking without OTP barriers': 'OTP అడ్డంకులు లేకుండా స్థితి ట్రాకింగ్',
  'ATR download as PDF': 'PDFగా ATR డౌన్‌లోడ్',
  'Automatic routing of grievances to designated GROs': 'నిర్దేశిత GROలకు ఫిర్యాదుల స్వయంచాలక మళ్లింపు',
  'Dynamic category-specific fields: LPG Consumer Number, USC Number, PPB Number, Job Card Number': 'డైనమిక్ వర్గ-నిర్దిష్ట ఫీల్డ్‌లు: LPG వినియోగదారు నంబర్, USC నంబర్, PPB నంబర్, జాబ్ కార్డ్ నంబర్',
  'Pre-formatted public hearing receipts — bulk and individual download': 'ముందుగా-రూపొందించిన బహిరంగ విచారణ రసీదులు — బల్క్ మరియు వ్యక్తిగత డౌన్‌లోడ్',
  'Inter-departmental tagging for coordinated cases': 'సమన్వయ కేసుల కోసం అంతర-శాఖా ట్యాగింగ్',
  'Multilingual receipts (Telugu)': 'బహుభాషా రసీదులు (తెలుగు)',
  'Critical gaps that remain': 'మిగిలిన కీలక లోపాలు',
  'No auto-escalation when ATR is not filed within 30 days': '30 రోజులలోపు ATR దాఖలు కానప్పుడు స్వయంచాలక ఎస్కలేషన్ లేదు',
  'No dedicated module for the Collector Appeal process': 'కలెక్టర్ అప్పీలు ప్రక్రియ కోసం అంకిత మాడ్యూల్ లేదు',
  'SMS notification on grievance filing stopped from January 2026': 'ఫిర్యాదు దాఖలుపై SMS నోటిఫికేషన్ జనవరి 2026 నుండి ఆగిపోయింది',
  'Hearing date / ATR / Mandal Prajavani notifications still pending despite October 2025 request': 'అక్టోబర్ 2025 అభ్యర్థన ఉన్నప్పటికీ విచారణ తేదీ / ATR / మండల ప్రజావాణి నోటిఫికేషన్లు ఇంకా పెండింగ్',
  'Citizen feedback on ATRs done outside the system (via SSAAT / Kisan Mitra phone calls and visits)': 'ATRలపై పౌర అభిప్రాయం వ్యవస్థ వెలుపల జరిగింది (SSAAT / కిసాన్ మిత్ర ఫోన్ కాల్స్ మరియు సందర్శనల ద్వారా)',
  'Status review framework (11 categories) built outside the portal by civil society': 'స్థితి సమీక్షా ఫ్రేమ్‌వర్క్ (11 వర్గాలు) పౌర సమాజం పోర్టల్ వెలుపల నిర్మించింది',
  'Citizen-centric design principle': 'పౌర-కేంద్రీకృత రూపకల్పన సూత్రం',
  'Technology cannot replace dialogue — but it can protect it': 'సాంకేతికత సంభాషణను భర్తీ చేయలేదు — కానీ దానిని రక్షించగలదు',
  'The portal triggers both a 30-day timeline and the right to a public hearing': 'పోర్టల్ 30-రోజుల గడువును మరియు బహిరంగ విచారణ హక్కును రెండింటిని ప్రేరేపిస్తుంది',
  'The role of technology was to record interactions properly, not to replace them': 'సాంకేతికత పాత్ర పరస్పర చర్యలను సరిగ్గా నమోదు చేయడమే, వాటిని భర్తీ చేయడం కాదు',

  // ─── SECTION 6: DIGITAL TECHNOLOGY ─────────────────────────────────────
  'What was built': 'ఏమి నిర్మించబడింది',
  'Friction & gaps': 'ఇబ్బందులు & లోపాలు',
  'Three learnings about technology and grievance redress': 'సాంకేతికత మరియు ఫిర్యాదు పరిష్కారం గురించి మూడు అభ్యాసాలు',
  'Pre-Pilot': 'పైలట్‌కు ముందు',
  'Phase 1': 'దశ 1',
  'Phase 2': 'దశ 2',
  'Phase 3': 'దశ 3',
  'Phase 4': 'దశ 4',
  'Outside': 'వెలుపల',
  'November 2024 — early discussions': 'నవంబర్ 2024 — తొలి చర్చలు',
  'Feb 2025 — testing through public hearings': 'ఫిబ్రవరి 2025 — బహిరంగ విచారణల ద్వారా పరీక్ష',
  'Mid-2025 — redesigning the portal': '2025 మధ్యకాలం — పోర్టల్ పునఃరూపకల్పన',
  'October 2025 — opening the portal to citizens': 'అక్టోబర్ 2025 — పౌరులకు పోర్టల్ తెరవడం',
  'Nov 2025 — transition to Weekly Mandal Prajavani': 'నవంబర్ 2025 — వారపు మండల ప్రజావాణికి మార్పు',
  'What was built outside the system': 'వ్యవస్థ వెలుపల ఏమి నిర్మించబడింది',
  'Initial discussions between CGG and civil society groups in November 2024 agreed core architectural elements. Grievance categories and sub-categories mapped to line departments. Directory mapping IFC operators, GROs, and Presiding Officers. Auto-assignment of grievances on filing. Mandatory text fields for GRO and Presiding Officer remarks. Independent logins for civil society volunteers.': 'నవంబర్ 2024లో CGG మరియు పౌర సమాజ సమూహాల మధ్య తొలి చర్చలు కీలక నిర్మాణ అంశాలపై అంగీకరించాయి. ఫిర్యాదు వర్గాలు మరియు ఉప-వర్గాలు లైన్ శాఖలకు మ్యాప్ చేయబడ్డాయి. IFC ఆపరేటర్లు, GROలు, అధ్యక్ష అధికారులను మ్యాప్ చేసే డైరెక్టరీ. దాఖలుపై ఫిర్యాదుల స్వయంచాలక కేటాయింపు. GRO మరియు అధ్యక్ష అధికారి వ్యాఖ్యలకు తప్పనిసరి టెక్స్ట్ ఫీల్డ్‌లు. పౌర సమాజ వాలంటీర్లకు స్వతంత్ర లాగిన్‌లు.',
  'The first sixteen hearings (6–14 February 2025) tested the digital system in the field. Several gaps surfaced quickly. Word mail-merge templates with Excel — generating 300–400 receipts a day manually — were the workaround until proper receipts were built into the portal.': 'మొదటి పదహారు విచారణలు (6–14 ఫిబ్రవరి 2025) డిజిటల్ వ్యవస్థను క్షేత్రంలో పరీక్షించాయి. అనేక లోపాలు వెంటనే బయటపడ్డాయి. పోర్టల్‌లో సరైన రసీదులు నిర్మించబడే వరకు Excelతో వర్డ్ మెయిల్-మెర్జ్ టెంప్లేట్లు — రోజుకు 300–400 రసీదులను చేతితో రూపొందించడం — తాత్కాలిక పరిష్కారంగా ఉన్నాయి.',
  'By mid-2025, workarounds were being built directly into the portal. Officers had repeatedly complained that grievance attachments lacked basic information — forcing them to call citizens. Drawing on the Kisan Mitra helpline practice of category-specific diagnostic questions, dynamic fields were added.': '2025 మధ్యకాలం నాటికి, తాత్కాలిక పరిష్కారాలు నేరుగా పోర్టల్‌లో నిర్మించబడుతున్నాయి. ఫిర్యాదు జత పత్రాలలో ప్రాథమిక సమాచారం లేదని అధికారులు పదేపదే ఫిర్యాదు చేశారు — ఇది వారిని పౌరులకు ఫోన్ చేసేలా చేసింది. వర్గ-నిర్దిష్ట నిర్ధారణ ప్రశ్నల కిసాన్ మిత్ర హెల్ప్‌లైన్ ఆచరణ ఆధారంగా, డైనమిక్ ఫీల్డ్‌లు జోడించబడ్డాయి.',
  'Until October 2025, the grievance-filing portal was not open to citizens. They could file only at IFCs or through panchayat-level volunteers. A formal request was submitted to the SNO Prajavani for four changes — converting information flows from primarily upward to downward and horizontal.': 'అక్టోబర్ 2025 వరకు, ఫిర్యాదు-దాఖలు పోర్టల్ పౌరులకు తెరవబడలేదు. వారు IFCలలో లేదా పంచాయితీ-స్థాయి వాలంటీర్ల ద్వారా మాత్రమే దాఖలు చేయగలిగారు. నాలుగు మార్పుల కోసం SNO ప్రజావాణికి అధికారిక అభ్యర్థన సమర్పించబడింది — సమాచార ప్రవాహాలను ప్రధానంగా పైకి నుండి కిందికి మరియు అడ్డంగా మార్చడం.',
  'When the system transitioned from monthly hearings to weekly Mandal Prajavani — where MPDOs often functioned as both Presiding Officer and GRO — the software did not adapt cleanly. Several features remained tied to the earlier monthly hearing workflow. CGG was already developing a unified statewide Prajavani portal to replace CPGRAMS, so the existing module was not redesigned specifically for Mandal Prajavani.': 'వ్యవస్థ నెలవారీ విచారణల నుండి వారపు మండల ప్రజావాణికి మారినప్పుడు — MPDOలు తరచుగా అధ్యక్ష అధికారి మరియు GRO రెండింటిగా పనిచేసిన చోట — సాఫ్ట్‌వేర్ సరిగ్గా అనుగుణం కాలేదు. అనేక లక్షణాలు పాత నెలవారీ విచారణ వర్క్‌ఫ్లోకు ముడిపడి ఉన్నాయి. CPGRAMSను భర్తీ చేయడానికి CGG అప్పటికే ఏకీకృత రాష్ట్రవ్యాప్త ప్రజావాణి పోర్టల్‌ను అభివృద్ధి చేస్తోంది, కాబట్టి ఇప్పటికే ఉన్న మాడ్యూల్ మండల ప్రజావాణి కోసం ప్రత్యేకంగా పునఃరూపకల్పన చేయబడలేదు.',
  'Several critical functions were never built into the portal — and ended up being handled by civil society on parallel systems. These gaps reveal what an institutional digital system would need to add.': 'అనేక కీలక విధులు పోర్టల్‌లో ఎన్నడూ నిర్మించబడలేదు — చివరికి సమాంతర వ్యవస్థలపై పౌర సమాజం వాటిని నిర్వహించింది. ఈ లోపాలు ఒక సంస్థాగత డిజిటల్ వ్యవస్థ ఏమి జోడించాల్సి ఉంటుందో వెల్లడిస్తాయి.',
  'Category → department mapping': 'వర్గం → శాఖ మ్యాపింగ్',
  'GRO and Presiding Officer directory': 'GRO మరియు అధ్యక్ష అధికారి డైరెక్టరీ',
  'Auto-assignment of grievances on filing': 'దాఖలుపై ఫిర్యాదుల స్వయంచాలక కేటాయింపు',
  'Mandatory remarks field for GRO and PO': 'GRO మరియు PO కోసం తప్పనిసరి వ్యాఖ్యల ఫీల్డ్',
  'Civil society volunteer logins for direct filing': 'ప్రత్యక్ష దాఖలు కోసం పౌర సమాజ వాలంటీర్ లాగిన్‌లు',
  'Mandatory remarks field forcing officer accountability': 'అధికారి జవాబుదారీతనాన్ని బలవంతం చేసే తప్పనిసరి వ్యాఖ్యల ఫీల్డ్',
  'Initial public hearing scheduling workflow': 'తొలి బహిరంగ విచారణ షెడ్యూలింగ్ వర్క్‌ఫ్లో',
  'Workaround templates for receipt generation': 'రసీదు రూపకల్పన కోసం తాత్కాలిక టెంప్లేట్లు',
  'GRO remarks were free-text — varied widely, often vague enough to defeat accountability': 'GRO వ్యాఖ్యలు స్వేచ్ఛా-వచనం — విస్తృతంగా మారాయి, తరచుగా జవాబుదారీతనాన్ని ఓడించేంత అస్పష్టంగా',
  'Public hearing receipts had to be generated outside the portal via Excel mail-merge': 'బహిరంగ విచారణ రసీదులను Excel మెయిల్-మెర్జ్ ద్వారా పోర్టల్ వెలుపల రూపొందించాల్సి వచ్చింది',
  'Officers’ handwritten remarks at hearings often could not be uploaded in real-time — broke the link to the ATR': 'విచారణల వద్ద అధికారుల చేతివ్రాత వ్యాఖ్యలను తరచుగా రియల్-టైంలో అప్‌లోడ్ చేయలేకపోయారు — ATRకు లింక్ తెగిపోయింది',
  'Citizens had to be informed of each hearing date separately — no fixed schedule': 'ప్రతి విచారణ తేదీని పౌరులకు విడిగా తెలియజేయాల్సి వచ్చింది — నిర్దిష్ట షెడ్యూల్ లేదు',
  'District approval required for each hearing — caused repeated delays': 'ప్రతి విచారణకు జిల్లా ఆమోదం అవసరం — పునరావృత ఆలస్యాలకు కారణమైంది',
  'Bulk and individual download of pre-formatted public hearing receipts': 'ముందుగా-రూపొందించిన బహిరంగ విచారణ రసీదుల బల్క్ మరియు వ్యక్తిగత డౌన్‌లోడ్',
  'Category-specific remark templates — Pensions, Gas Subsidy, Gruhajyothi, Crop Loan Waiver (3–4 options + "Other")': 'వర్గ-నిర్దిష్ట వ్యాఖ్య టెంప్లేట్లు — పెన్షన్లు, గ్యాస్ సబ్సిడీ, గృహజ్యోతి, పంట రుణ మాఫీ (3–4 ఎంపికలు + "ఇతర")',
  'Dynamic category-specific input fields: LPG Consumer Number, USC Number, PPB Number, Job Card Number': 'డైనమిక్ వర్గ-నిర్దిష్ట ఇన్‌పుట్ ఫీల్డ్‌లు: LPG వినియోగదారు నంబర్, USC నంబర్, PPB నంబర్, జాబ్ కార్డ్ నంబర్',
  'Admin login for District Collector to edit category fields and templates': 'వర్గ ఫీల్డ్‌లు మరియు టెంప్లేట్లను సవరించడానికి జిల్లా కలెక్టర్‌కు అడ్మిన్ లాగిన్',
  'One-ATR rule — only one final ATR per grievance, with an "Interim Reply" field for partial updates': 'ఒక-ATR నియమం — ఫిర్యాదుకు ఒకే తుది ATR, పాక్షిక నవీకరణల కోసం "మధ్యంతర సమాధానం" ఫీల్డ్‌తో',
  'One-ATR rule creates visibility gap for grievances moving through multiple bureaucratic levels': 'బహుళ బ్యూరోక్రాటిక్ స్థాయుల గుండా వెళ్లే ఫిర్యాదులకు ఒక-ATR నియమం దృశ్యమానత లోపాన్ని సృష్టిస్తుంది',
  'A mandal officer may file a "final" ATR while case still needs district/state action — citizens left unclear on next steps': 'కేసుకు ఇంకా జిల్లా/రాష్ట్ర చర్య అవసరమైనప్పటికీ ఒక మండల అధికారి "తుది" ATR దాఖలు చేయవచ్చు — తదుపరి దశలపై పౌరులకు స్పష్టత ఉండదు',
  'Editing functionality created some dependence on CGG team in Hyderabad for changes': 'సవరణ సౌకర్యం మార్పుల కోసం హైదరాబాద్‌లోని CGG బృందంపై కొంత ఆధారపడటాన్ని సృష్టించింది',
  'Direct filing by citizens with mobile OTP authentication': 'మొబైల్ OTP ప్రామాణీకరణతో పౌరులు నేరుగా దాఖలు చేయడం',
  'ATR download communicated directly to complainants': 'ATR డౌన్‌లోడ్ నేరుగా ఫిర్యాదుదారులకు తెలియజేయబడుతుంది',
  'Dashboard for District Officers to monitor mandal-level ATR filing': 'మండల-స్థాయి ATR దాఖలును పర్యవేక్షించడానికి జిల్లా అధికారులకు డాష్‌బోర్డ్',
  'Auto-escalation when ATR not filed within 30 days — still not implemented': '30 రోజులలోపు ATR దాఖలు కానప్పుడు స్వయంచాలక ఎస్కలేషన్ — ఇంకా అమలు కాలేదు',
  'Dedicated software module for Collector Appeal — still not built': 'కలెక్టర్ అప్పీలు కోసం అంకిత సాఫ్ట్‌వేర్ మాడ్యూల్ — ఇంకా నిర్మించబడలేదు',
  'Inter-departmental tagging for cases requiring multi-officer coordination — partial': 'బహుళ-అధికారి సమన్వయం అవసరమైన కేసుల కోసం అంతర-శాఖా ట్యాగింగ్ — పాక్షికం',
  'GROs cannot attach files when filing Interim Replies': 'మధ్యంతర సమాధానాలు దాఖలు చేసేటప్పుడు GROలు ఫైళ్లను జతచేయలేరు',
  'Citizen notifications (SMS / Telugu) — partial; automatic SMS on filing stopped Jan 2026': 'పౌర నోటిఫికేషన్లు (SMS / తెలుగు) — పాక్షికం; దాఖలుపై స్వయంచాలక SMS జనవరి 2026లో ఆగిపోయింది',
  'Continued use of public-hearing receipt format for Mandal Prajavani sessions': 'మండల ప్రజావాణి సెషన్ల కోసం బహిరంగ-విచారణ రసీదు ఫార్మాట్ కొనసాగింపు',
  'Same workflow extended to weekly cadence': 'అదే వర్క్‌ఫ్లో వారపు లయకు విస్తరించబడింది',
  'Receipt format was designed for monthly hearings — not optimal for weekly use': 'రసీదు ఫార్మాట్ నెలవారీ విచారణల కోసం రూపొందించబడింది — వారపు ఉపయోగానికి అనుకూలం కాదు',
  'When MPDO functions as both PO and GRO, the dual-role workflow is awkward': 'MPDO PO మరియు GRO రెండింటిగా పనిచేసినప్పుడు, ద్వంద్వ-పాత్ర వర్క్‌ఫ్లో ఇబ్బందికరం',
  'A statewide unified portal is being built — delaying further pilot-specific changes': 'రాష్ట్రవ్యాప్త ఏకీకృత పోర్టల్ నిర్మించబడుతోంది — తదుపరి పైలట్-నిర్దిష్ట మార్పులను ఆలస్యం చేస్తోంది',
  'Citizen feedback on ATRs — SSAAT and Kisan Mitra phone calls and panchayat visits': 'ATRలపై పౌర అభిప్రాయం — SSAAT మరియు కిసాన్ మిత్ర ఫోన్ కాల్స్ మరియు పంచాయితీ సందర్శనలు',
  'Status review and aggregation framework — 11 ATR status categories developed by civil society review team': 'స్థితి సమీక్ష మరియు సమగ్రీకరణ ఫ్రేమ్‌వర్క్ — పౌర సమాజ సమీక్షా బృందం అభివృద్ధి చేసిన 11 ATR స్థితి వర్గాలు',
  'Custom IT system for documenting field follow-up (built by July 2025)': 'క్షేత్ర ఫాలో-అప్‌ను నమోదు చేయడానికి ప్రత్యేక IT వ్యవస్థ (జూలై 2025 నాటికి నిర్మించబడింది)',
  'Hearing notifications — Exotel cloud-based voice calls + Panchayat Secretary calls': 'విచారణ నోటిఫికేషన్లు — Exotel క్లౌడ్-ఆధారిత వాయిస్ కాల్స్ + పంచాయితీ కార్యదర్శి కాల్స్',
  'PNG WhatsApp accountability reports for mandal officers — weekly ATR pendency leaderboards': 'మండల అధికారుల కోసం PNG వాట్సాప్ జవాబుదారీ నివేదికలు — వారపు ATR పెండింగ్ లీడర్‌బోర్డులు',
  'Feedback data is not integrated into official portal': 'అభిప్రాయ డేటా అధికారిక పోర్టల్‌లో సమైక్యం కాలేదు',
  '11-status framework remains civil-society-maintained, not institutional': '11-స్థితి ఫ్రేమ్‌వర్క్ సంస్థాగతం కాదు, పౌర-సమాజం-నిర్వహించేదిగా ఉంది',
  'When civil society withdraws, these functions disappear with them': 'పౌర సమాజం వైదొలిగినప్పుడు, ఈ విధులు వాటితో పాటు అదృశ్యమవుతాయి',
  'Software shapes practice more than instructions do': 'సూచనల కంటే సాఫ్ట్‌వేర్ ఆచరణను ఎక్కువగా రూపొందిస్తుంది',
  'Regardless of the SOP, officers act on what their login screen prompts them to do. Building accountability into the workflow — mandatory remarks fields, category-specific inputs — produced more behavioural change than training alone.': 'SOP ఏమైనప్పటికీ, అధికారులు తమ లాగిన్ స్క్రీన్ సూచించిన దాని ప్రకారం చర్య తీసుకుంటారు. వర్క్‌ఫ్లోలో జవాబుదారీతనాన్ని నిర్మించడం — తప్పనిసరి వ్యాఖ్యల ఫీల్డ్‌లు, వర్గ-నిర్దిష్ట ఇన్‌పుట్‌లు — శిక్షణ కంటే ఎక్కువ ప్రవర్తనా మార్పును సృష్టించింది.',
  'Build around the citizen, not the back-end': 'బ్యాక్-ఎండ్ కాదు, పౌరుని చుట్టూ నిర్మించండి',
  'The decisions that mattered most — mobile-OTP filing without barriers, status tracking without OTPs, printed Telugu receipts, dynamic category-specific fields — came from keeping citizens’ needs at the forefront, not top-down administrative control.': 'అత్యంత ముఖ్యమైన నిర్ణయాలు — అడ్డంకులు లేకుండా మొబైల్-OTP దాఖలు, OTPలు లేకుండా స్థితి ట్రాకింగ్, ముద్రిత తెలుగు రసీదులు, డైనమిక్ వర్గ-నిర్దిష్ట ఫీల్డ్‌లు — పై-నుండి-కింది పరిపాలనా నియంత్రణ కాదు, పౌరుల అవసరాలను ముందుంచడం నుండి వచ్చాయి.',
  'Technology cannot replace dialogue, but it can protect it': 'సాంకేతికత సంభాషణను భర్తీ చేయలేదు, కానీ దానిని రక్షించగలదు',
  'The most effective feature of the Pilot was the public hearing — direct interaction between citizens and officials. The role of technology was to ensure these interactions were properly recorded, tracked, and followed through within defined timelines.': 'పైలట్ యొక్క అత్యంత ప్రభావవంతమైన లక్షణం బహిరంగ విచారణ — పౌరులు మరియు అధికారుల మధ్య ప్రత్యక్ష పరస్పర చర్య. ఈ పరస్పర చర్యలు సరిగ్గా నమోదు చేయబడి, ట్రాక్ చేయబడి, నిర్దిష్ట గడువుల్లో అనుసరించబడేలా చూడటం సాంకేతికత పాత్ర.',

  // ─── SECTION 7: FOLLOW-UP MECHANISM ────────────────────────────────────
  'Grievances followed up by SSAAT + civil society (as of 18 April 2026)': 'SSAAT + పౌర సమాజం ఫాలో-అప్ చేసిన ఫిర్యాదులు (18 ఏప్రిల్ 2026 నాటికి)',
  'status': 'స్థితి',
  'statuses': 'స్థితులు',
  'Positively Disposed': 'సానుకూలంగా పరిష్కరించబడింది',
  'Sent to Next Level': 'తదుపరి స్థాయికి పంపబడింది',
  'Appeal': 'అప్పీలు',
  'Policy Decision Awaited': 'విధాన నిర్ణయం కోసం ఎదురుచూపు',
  'Others': 'ఇతరాలు',
  'Disposed (Resolved)': 'పరిష్కరించబడింది (పరిష్కారం)',
  'The citizen is now receiving the entitlement / benefit.': 'పౌరుడు ఇప్పుడు హక్కు / ప్రయోజనాన్ని అందుకుంటున్నారు.',
  'Disposed (Ineligible)': 'పరిష్కరించబడింది (అనర్హం)',
  'The citizen does not meet the eligibility criteria of the scheme.': 'పౌరుడు పథకం యొక్క అర్హతా ప్రమాణాలను తీర్చడం లేదు.',
  'Disposed (Civil Dispute)': 'పరిష్కరించబడింది (పౌర వివాదం)',
  'The grievance is a subject-matter of a civil dispute, or can be dealt with only through a civil dispute.': 'ఫిర్యాదు ఒక పౌర వివాద విషయం, లేదా పౌర వివాదం ద్వారా మాత్రమే పరిష్కరించదగినది.',
  'Pending (citizen action / info awaited)': 'పెండింగ్ (పౌర చర్య / సమాచారం కోసం ఎదురుచూపు)',
  'The citizen is yet to obtain and / or submit necessary documentation for redressal.': 'పౌరుడు పరిష్కారానికి అవసరమైన పత్రాలను పొంది మరియు / లేదా సమర్పించాల్సి ఉంది.',
  'Disposed (Sent to District level)': 'పరిష్కరించబడింది (జిల్లా స్థాయికి పంపబడింది)',
  'The GRO has processed the grievance and sent it to the District-level Officer for further action.': 'GRO ఫిర్యాదును ప్రాసెస్ చేసి తదుపరి చర్య కోసం జిల్లా-స్థాయి అధికారికి పంపారు.',
  'Disposed (Sent to State level)': 'పరిష్కరించబడింది (రాష్ట్ర స్థాయికి పంపబడింది)',
  'The GRO has processed the grievance and sent it to the State-level Officer for further action.': 'GRO ఫిర్యాదును ప్రాసెస్ చేసి తదుపరి చర్య కోసం రాష్ట్ర-స్థాయి అధికారికి పంపారు.',
  'No ATR filed beyond the 30-day limit, or ATR filed in non-compliance with the SoP or wrongly for other reasons.': '30-రోజుల పరిమితి దాటి ఏ ATR దాఖలు కాలేదు, లేదా SoPకి విరుద్ధంగా లేదా ఇతర కారణాల వల్ల తప్పుగా ATR దాఖలు చేయబడింది.',
  'Disposed (Policy Decision)': 'పరిష్కరించబడింది (విధాన నిర్ణయం)',
  'The elected government is yet to make a policy decision on the scheme or service.': 'ఎన్నికైన ప్రభుత్వం పథకం లేదా సేవపై విధాన నిర్ణయం తీసుకోవాల్సి ఉంది.',
  'Disposed (burden shifted on citizen)': 'పరిష్కరించబడింది (భారం పౌరునిపై మోపబడింది)',
  'The GRO wrongly places the burden of the grievance redress process on the citizen, in non-compliance with the SoP.': 'GRO SoPకి విరుద్ధంగా, ఫిర్యాదు పరిష్కార ప్రక్రియ భారాన్ని తప్పుగా పౌరునిపై మోపుతారు.',
  'Pending (at mandal level)': 'పెండింగ్ (మండల స్థాయిలో)',
  'The citizen has submitted the necessary documentation as requested by the GRO and action is yet to be taken by the GRO.': 'GRO అడిగినట్టుగా పౌరుడు అవసరమైన పత్రాలను సమర్పించారు, GRO ఇంకా చర్య తీసుకోవాల్సి ఉంది.',
  'Wrong Category / Grievance': 'తప్పు వర్గం / ఫిర్యాదు',
  'The grievance was filed wrongly.': 'ఫిర్యాదు తప్పుగా దాఖలు చేయబడింది.',
  'Field verification': 'క్షేత్ర సత్యాపన',
  'SSAAT resource persons and Kisan Mitra volunteers visit the complainant. Verify whether the ATR is accurate and implemented. Identify gaps in scheme design.': 'SSAAT వనరుల వ్యక్తులు మరియు కిసాన్ మిత్ర వాలంటీర్లు ఫిర్యాదుదారుని సందర్శిస్తారు. ATR ఖచ్చితమైనదా మరియు అమలు చేయబడిందా అని ధృవీకరిస్తారు. పథక రూపకల్పనలోని లోపాలను గుర్తిస్తారు.',
  'SSAAT + Kisan Mitra resource persons': 'SSAAT + కిసాన్ మిత్ర వనరుల వ్యక్తులు',
  'Custom IT system entry': 'ప్రత్యేక IT వ్యవస్థ నమోదు',
  'Findings entered into a separate civil-society-built IT system (built by July 2025). Records next steps, current pending level, follow-up medium.': 'ఫలితాలు పౌర-సమాజం-నిర్మించిన ప్రత్యేక IT వ్యవస్థలో నమోదు చేయబడతాయి (జూలై 2025 నాటికి నిర్మించబడింది). తదుపరి దశలు, ప్రస్తుత పెండింగ్ స్థాయి, ఫాలో-అప్ మాధ్యమాన్ని నమోదు చేస్తుంది.',
  'Civil society review team': 'పౌర సమాజ సమీక్షా బృందం',
  'Desk-based lifecycle review': 'డెస్క్-ఆధారిత జీవితచక్ర సమీక్ష',
  'A 5–7 member civil society desk team examines the entire lifecycle: grievance → GRO enquiry → Mandal Prajavani remarks → ATR → field verification. Assigns one of 11 status categories.': 'ఒక 5–7 మంది పౌర సమాజ డెస్క్ బృందం మొత్తం జీవితచక్రాన్ని పరిశీలిస్తుంది: ఫిర్యాదు → GRO విచారణ → మండల ప్రజావాణి వ్యాఖ్యలు → ATR → క్షేత్ర సత్యాపన. 11 స్థితి వర్గాలలో ఒకటి కేటాయిస్తుంది.',
  'Civil society desk team': 'పౌర సమాజ డెస్క్ బృందం',
  'Outcome': 'ఫలితం',
  'Status assigned: Resolved, Sent to Next Level, Marked for Collector Appeal, Policy Decision Awaited, or Other. Feeds the report\'s analytical framework.': 'స్థితి కేటాయించబడింది: పరిష్కరించబడింది, తదుపరి స్థాయికి పంపబడింది, కలెక్టర్ అప్పీలు కోసం మార్క్ చేయబడింది, విధాన నిర్ణయం కోసం ఎదురుచూపు, లేదా ఇతర. నివేదిక యొక్క విశ్లేషణాత్మక ఫ్రేమ్‌వర్క్‌కు ఆధారం.',
  'Review framework': 'సమీక్షా ఫ్రేమ్‌వర్క్',
  'Society for Social Audit, Accountability and Transparency — a Telangana Government social audit unit': 'సొసైటీ ఫర్ సోషల్ ఆడిట్, అకౌంటబిలిటీ అండ్ ట్రాన్స్‌పరెన్సీ — తెలంగాణ ప్రభుత్వ సామాజిక తనిఖీ విభాగం',
  'Lead field verification — every closed grievance': 'క్షేత్ర సత్యాపనకు నాయకత్వం — ప్రతి మూసివేయబడిన ఫిర్యాదు',
  'Field-verify ATR claims': 'ATR వాదనలను క్షేత్రంలో ధృవీకరించడం',
  'Maintain master review dataset': 'మాస్టర్ సమీక్షా డేటాసెట్‌ను నిర్వహించడం',
  'Flag wrong-ATR cases for Collector Appeal': 'తప్పు-ATR కేసులను కలెక్టర్ అప్పీలు కోసం గుర్తించడం',
  'Identify ATR template misuse (e.g. mechanical succession remarks for non-succession grievances)': 'ATR టెంప్లేట్ దుర్వినియోగాన్ని గుర్తించడం (ఉదా. వారసత్వేతర ఫిర్యాదులకు యాంత్రిక వారసత్వ వ్యాఖ్యలు)',
  'Civil society organisation focused on agricultural livelihoods': 'వ్యవసాయ జీవనోపాధులపై దృష్టి పెట్టిన పౌర సమాజ సంస్థ',
  'Citizen mobilisation + agricultural grievance follow-up': 'పౌర సమీకరణ + వ్యవసాయ ఫిర్యాదు ఫాలో-అప్',
  'Mobilise complainants — especially women, elders, tribal communities': 'ఫిర్యాదుదారులను సమీకరించడం — ముఖ్యంగా మహిళలు, వృద్ధులు, గిరిజన సమాజాలు',
  'Follow up on pension, MGNREGA, Crop Loan Waiver, PM Kisan cases': 'పెన్షన్, MGNREGA, పంట రుణ మాఫీ, పీఎం కిసాన్ కేసులపై ఫాలో-అప్',
  'Conduct phone-based and panchayat-level follow-up': 'ఫోన్-ఆధారిత మరియు పంచాయితీ-స్థాయి ఫాలో-అప్ నిర్వహించడం',
  'Over 60 volunteers from across the country — including law and policy students': 'దేశం అంతటి నుండి 60కి పైగా వాలంటీర్లు — న్యాయ మరియు విధాన విద్యార్థులతో సహా',
  'Pilot rollout, ongoing support, and desk review': 'పైలట్ అమలు, కొనసాగుతున్న మద్దతు, మరియు డెస్క్ సమీక్ష',
  'CCD, CPF, DEF, RSV, MKSS, Dalit Bahujan Front, SAFA, SAFAR': 'CCD, CPF, DEF, RSV, MKSS, దళిత బహుజన ఫ్రంట్, SAFA, SAFAR',
  'Specialised support — IFR cases (CPF), MGNREGA (MKSS)': 'ప్రత్యేక మద్దతు — IFR కేసులు (CPF), MGNREGA (MKSS)',
  'Joined for Feb 2025 hearings; ongoing rotational support': 'ఫిబ్రవరి 2025 విచారణల కోసం చేరారు; కొనసాగుతున్న రొటేషనల్ మద్దతు',
  'Students assist the 5–7 member desk team in reviewing every grievance\'s lifecycle and assigning one of the 11 status categories': 'విద్యార్థులు ప్రతి ఫిర్యాదు జీవితచక్రాన్ని సమీక్షించడంలో మరియు 11 స్థితి వర్గాలలో ఒకటి కేటాయించడంలో 5–7 మంది డెస్క్ బృందానికి సహాయం చేస్తారు',
  'Pendor Vinod Kumar, Kisan Mitra Helpline, Adilabad': 'పెందూర్ వినోద్ కుమార్, కిసాన్ మిత్ర హెల్ప్‌లైన్, ఆదిలాబాద్',
  '"Many citizens know their issues, but the concerned officers often do not take timely action. Officers ask citizens to wait for one or two days. When the citizen returns, they are told that the officer is not available or is busy, and they are asked to come again the following week. Such incidents happen frequently, especially in rural areas. Due to these continuous delays and lack of proper guidance, we are working to support citizens at the grassroots level — through proper follow-up and coordination with the concerned departments."': '"చాలామంది పౌరులకు తమ సమస్యలు తెలుసు, కానీ సంబంధిత అధికారులు తరచుగా సకాలంలో చర్య తీసుకోరు. అధికారులు పౌరులను ఒకటి రెండు రోజులు వేచి ఉండమని అడుగుతారు. పౌరుడు తిరిగి వచ్చినప్పుడు, అధికారి అందుబాటులో లేరని లేదా బిజీగా ఉన్నారని చెప్పి, మళ్లీ వచ్చే వారం రమ్మని అడుగుతారు. ఇలాంటి సంఘటనలు తరచుగా జరుగుతాయి, ముఖ్యంగా గ్రామీణ ప్రాంతాల్లో. ఈ నిరంతర ఆలస్యాలు మరియు సరైన మార్గదర్శకత్వం లేకపోవడం వల్ల, మేము క్షేత్ర స్థాయిలో పౌరులకు మద్దతు ఇవ్వడానికి పనిచేస్తున్నాము — సరైన ఫాలో-అప్ మరియు సంబంధిత శాఖలతో సమన్వయం ద్వారా."',

};
